# Generated by Django 6.0.3 on 2026-04-20 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeManagementSys', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='std',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='std',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculties', to='CollegeManagementSys.department'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='CollegeManagementSys.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
