# Generated by Django 6.0.3 on 2026-04-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeManagementSys', '0003_rename_std_leave_student_rename_std_semester_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
