# Generated by Django 6.0.3 on 2026-04-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeManagementSys', '0004_remove_student_user_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
