# Generated by Django 6.0.3 on 2026-04-23 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeManagementSys', '0006_remove_faculty_user_faculty_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='fee',
            name='status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CollegeManagementSys.student'),
        ),
    ]
