# Generated by Django 6.0.3 on 2026-08-21 10:21

import CollegeManagementSys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeManagementSys', '0014_remove_student_academic_year_remove_user_student_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', CollegeManagementSys.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hod', 'HOD'), ('faculty', 'Faculty'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
