# Generated by Django 6.0.3 on 2026-04-23 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeManagementSys', '0007_remove_fee_created_at_alter_fee_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='CollegeManagementSys.faculty'),
        ),
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='CollegeManagementSys.student'),
        ),
    ]
