# Generated by Django 6.0.3 on 2026-04-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeManagementSys', '0008_user_faculty_user_student'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fee',
            unique_together={('student', 'academic_year')},
        ),
    ]
