# Generated by Django 6.0.3 on 2026-04-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeManagementSys', '0009_alter_fee_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
